if (MSVC)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W2 /MP")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /DEBUG /Od")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2")
	string(REGEX REPLACE "\\/W3" " " CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
	add_compile_options(/wd4068)
	add_compile_options(/wd4319)
	add_compile_options(/wd4251)
	add_compile_options(/wd4275)

	message(STATUS ${CMAKE_CXX_FLAGS})
	message(STATUS ${CMAKE_CXX_FLAGS_DEBUG})
	message(STATUS ${CMAKE_CXX_FLAGS_RELEASE})
	message(STATUS ${CMAKE_CXX_FLAGS_MINSIZEREL})
	message(STATUS ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})

elseif (MINGW)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -fPIC -Wno-unknown-pragmas -Wno-shift-count-overflow")
	set(CMAKE_CXX_FLAGS_DEBUG "-g -O0")
	set(CMAKE_CXX_FLAGS_RELEASE "-O3")
else ()
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -fPIC -Wextra -pedantic -Wno-unknown-pragmas -Wno-unused-parameter -Wno-shift-count-overflow")
	set(CMAKE_CXX_FLAGS_DEBUG "-g -O0")
	set(CMAKE_CXX_FLAGS_RELEASE "-O3")
	message(STATUS ${CMAKE_CXX_FLAGS})
	message(STATUS ${CMAKE_CXX_FLAGS_DEBUG})
	message(STATUS ${CMAKE_CXX_FLAGS_RELEASE})
endif ()